### ISSUE TITLE
Ready for grading week 2 assignment

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#1]

**Comment by cethenmc** [comment]
Hi, Brianna:  Week 2, assignment #1 is great.  However, I would like you to make an enhancement on Week 2, assignment #2 (first-script.py).

I would like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
    1. modify the file in NetLab with the added line at the top.
    2. update the file to be executable.
    3. add the file to staging (git add .)
    4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
    5. push to the git hub repository (git push)
    6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by bmiller11-matc** [comment]
changes made

**Comment by bmiller11-matc** [comment]
permissions changed, use the firstscript file not the first-script

**Comment by cethenmc** [comment]
Thank you, Brianna!
