### ISSUE TITLE
week 9 f2c.py ready for grading

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#11]

**Comment by cethenmc** [comment]
Hi, Brianna.  Recorded a 2 of 8 for now.  When I pulled from GitHub only a single file came down for Week 9 (i.e., f2c.py).  You may resubmit soon with completed requirements for full credit.

![image](https://user-images.githubusercontent.com/112707666/200007100-03f666fb-4405-4dde-a27d-f7710ed03f74.png)

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208516781-151839ee-a482-4a54-8a1b-656689a2e962.png)
