### ISSUE TITLE
week 11 arguments.py ready for grading

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#13]

**Comment by cethenmc** [comment]
Some good work setting up many of the arguments.  Others need slight tweaking.  Please submit corrections soon to have an opportunity for full credit, as I have recorded a 5 out of 8 for now.  Here are some hints to help you...

When I run your help menu, I see an extra M, BASIC, and 2 VERSION.
Running ./arguments.py -v is not working, and the keyword to return the version is not in it.
Line 16 has a yellow underline indicating something is wrong.
One of your boolean should default to True...do you know which one?
You were asked to print 4 specific arguments out, not the whole arg.
Defaults were not required (except for the booleans, of course).  No points lost on this, but if you go into adjust code, perhaps you can clear those that are unnecessary.

Thanks.

Chris

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/208516752-5beeb3c5-3807-45e2-be54-7da6bcf71f78.png)
