### ISSUE TITLE
Week 3 assignment ready for grading

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#2]

**Comment by cethenmc** [comment]
Hi, Brianna.  This assignment also does not have permission to run at the command line.  Will you please reply to this issue ticket when you get the permission changed and re-pushed to GitHub?  Thanks.  ~Chris

**Comment by bmiller11-matc** [comment]
permissions changed

**Comment by cethenmc** [comment]
Please fix the script.
#6 - wrong symbol
varLoot is the wrong value
#12 should not have hardcoded $ except for using as a fill character in the formatted string
#13 is skipped.

Please reach out if you have questions.

**Comment by cethenmc** [comment]
Hi, Brianna.  I am going to record 7/8.  The spacing on #12 and #13 still does not match the assignment.  I will still allow you to get 8 out of 8, but you should consider pulling down the Word document assignment and counting out the spaces and the dollar signs before you resubmit.  Please don't forget the suitable spaces between the ending bracket and the beginning bracket of the following color, as well.

Thanks.

Chris

**Comment by cethenmc** [comment]
Hi, Brianna.  Do you want me to just keep the 7 of 8 or do you want to correct and repush this script to GitHub for full credit?  Please reply with either decision to this Issue Ticket.  Thanks. ~Chris

**Comment by bmiller11-matc** [comment]
keep this grade

**Comment by cethenmc** [comment]
Thanks for confirming.  I will keep this grade and will close this issue.
