### ISSUE TITLE
Week 6: Lab 2 flow control ready for grading

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#6]

**Comment by cethenmc** [comment]
Hi, Brianna.  You made a lot of the other your own, which is nice (and perhaps a little eerie:-D).  However, you have nothing under door 3.  It renders the same result as if you choose door 4 which does not exist.  I will record 4 of 8 for now, but please provide options under the third door you created and repush to GitHub for full credit.  PLEASE reply to this ticket when your changes are ready for grading.

**$ ./flowControl.py** 
You enter a shadowy hallway. Three of the doors are open.
One is a bathroom, one is a bedroom, and one is some kind of closet.
Which do you enter?
-> **3**
You choose to stand there, twiddling your thumbs.
I guess you have nothing better to do.

**$ ./flowControl.py** 
You enter a shadowy hallway. Three of the doors are open.
One is a bathroom, one is a bedroom, and one is some kind of closet.
Which do you enter?
-> **4**
You choose to stand there, twiddling your thumbs.
I guess you have nothing better to do.

Thanks.

Chris

**Comment by bmiller11-matc** [comment]
i had it set so you had to type in the name of the room. i updated the file with door numbers, now both options work.

**Comment by cethenmc** [comment]
oh my gosh, not sure how I missed that.  I entered "closet" on your old version and voila.  I apologize.  I should know not to work late on a Friday evening.  Nice work.  Full credit.
