### ISSUE TITLE
midterm-if.py ready for grading

### ISSUE THREAD

**Issue by bmiller11-matc** [madisoncollege-it-programs/python-scripting-bmiller11-matc#8]

**Comment by cethenmc** [comment]
Midterm-if:  I like the creativity of using a concept we did not learn in this class yet by this point.  It is brilliant to have chosen to use the 'any' function.  However, some required components were missed.  The line number in the ID column in the file was to be extracted (2 pt) and converted to an int (2 pt); if the lines were not in sequential order, then the extraction would not work.  Move one line in the file to another location, and you will receive a different answer than if you added the line numbers.  I usually take two points for not using the if/elifs that were required.  However, using 'any' does treat the logic the same way.  As a result, I will only deduct 1 pt.  Your score is 28/33.
